version: "3.8"

services:  
  backend:
    image: ${CI_REGISTRY_IMAGE}/momo-backend:${VERSION}
    container_name: momo-backend
    expose:
      - "8081"
    healthcheck:
      test: curl --fail -s http://localhost:8081/health
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - momo-network
    restart: unless-stopped

  frontend:
    image: ${CI_REGISTRY_IMAGE}/momo-frontend:${VERSION}
    container_name: momo-frontend
    ports:
      - "80:80"
    networks:
      - momo-network
    #volumes:
    #  - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  momo-network:
    driver: bridge