# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    {{ .Values.global.dockerconfigjson | default "default-value" }}
type: kubernetes.io/dockerconfigjson