---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: momo-backend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: momo-backend
  updatePolicy:
    # VPA не меняет ничего, только записывает рекомендации в статус объекта VerticalPodAutoscaler
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 0m
          memory: 0Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits