---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-backend
  labels:
    app: momo-backend
spec:
  replicas: 1
  # сохранение историй ревизий
  revisionHistoryLimit: 12
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "20%"
  selector:
    matchLabels:
      app: momo-backend
  template:
    metadata:
      labels:
        app: momo-backend
    # шаблон для создания Pod'ов
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-int-005-006/momo-store/momo-backend:1.0.2327684
          name: momo-store-backend
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              #memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              #memory: "128Mi"
              cpu: "200m"
          ports:
            - name: momo-backend
              containerPort: 8081
          livenessProbe:
            # проверка живучести curl --fail -s http://localhost:8081/health
            exec:
              command:
              - curl
              - --fail
              - -silent
              - http://localhost:8081/health
            # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
            initialDelaySeconds: 15
            # период выполнения проверки
            periodSeconds: 30
            # максимальное время выполнения проверки (по умолчанию 1 раз)
            timeoutSeconds: 5
            # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
            failureThreshold: 6
      # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
      imagePullSecrets:
        - name: docker-config-secret