#cloud-config
#https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - default
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh-key}
    
