---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: '{{ .Values.slack_hook_url }}'
    route:
       group_wait: 10s
       group_interval: 30s
       repeat_interval: 30m
       receiver: "slack"
       routes:
         - receiver: "slack"
           group_wait: 10s
           match_re:
             severity: critical|warning
           continue: true
    receivers:
     - name: "slack"
       slack_configs:
         - send_resolved: true
           channel: '{{ .Values.slack_channel }}'
           text: "{{ "{{" }} range .Alerts {{ "}}" }}{{ "{{" }} .Annotations.summary {{ "}}" }}\n{{ "{{" }} .Annotations.description }}\n{{ "{{" }} end {{ "}}" }}"
